<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_signatory_email</name>
   <tag></tag>
   <elementGuidId>31c56e24-580f-4903-91db-6be07af93be6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputSignatoryEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputSignatoryEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>839da40e-4744-467d-ab1a-6e7000f78346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>30cd2178-37eb-4d46-af0a-f4bba94ef7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c1cfab93-2777-42bb-b4fb-64ade6bed20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control minor-edit error</value>
      <webElementGuid>106ac7c2-407c-4434-90fe-a508a2997ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputSignatoryEmail</value>
      <webElementGuid>aef122f6-9814-41f8-b811-b33d584b57a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signatory_email</value>
      <webElementGuid>7e75f38c-1a54-4bd8-a523-eb3e06b2dd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputSignatoryEmail&quot;)</value>
      <webElementGuid>4ebfac32-2a2f-4996-b52d-fd2617df19cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputSignatoryEmail']</value>
      <webElementGuid>4cbb0455-2ffb-4667-8d4a-9b9dfef71d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-2']/div[2]/div[3]/div/input</value>
      <webElementGuid>4b825a0e-8a98-416d-8032-2403103d48b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/div/input</value>
      <webElementGuid>e5bcb582-d72b-4fac-b785-b811373a3393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputSignatoryEmail' and @name = 'signatory_email']</value>
      <webElementGuid>c1f98551-dfba-47dd-8fca-a25e041dded2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
