<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Same as company address_address_same__59d90d</name>
   <tag></tag>
   <elementGuidId>abdc9c4a-57b5-46f2-b311-eea98f9367f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sameCompanyAddressCheck']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sameCompanyAddressCheck</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3abe331-da86-463a-9ed0-f39a213db06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>bae2d99f-6062-4517-9b42-307b8d0590d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>29186cee-3722-4c25-b3e1-edd5ea534d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address_same_as_company</value>
      <webElementGuid>2bccd11e-8eb9-4da3-a61e-2a9e0892b33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sameCompanyAddressCheck</value>
      <webElementGuid>c9dabe18-7d70-42ed-ae49-d718365e4790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sameCompanyAddressCheck&quot;)</value>
      <webElementGuid>f474e146-6933-4e6d-aec8-bc4de4d1d293</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sameCompanyAddressCheck']</value>
      <webElementGuid>539dd614-3f7e-4cfd-a702-f663d197f452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-2']/div[2]/div[6]/div/div/label/input</value>
      <webElementGuid>484f09cd-46da-4c07-9ef5-9990c5f2f47f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/label/input</value>
      <webElementGuid>eda2a05f-041d-4b4a-bcdf-e8dd87e1fc66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'address_same_as_company' and @id = 'sameCompanyAddressCheck']</value>
      <webElementGuid>c2c90ed1-01ad-469f-bdfb-2054d996620a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
