<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>d63ba824-a9b5-47ff-b3d7-b6f64d64ecd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick=&quot;redirect_overlay('https://stage.mobipaid.com/login')&quot;])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-xs-6.have-account-text.padding-login-link > center > a.login-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ceedb0ea-b524-4abd-a3a4-b8a5a4613dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>redirect_overlay('https://stage.mobipaid.com/login')</value>
      <webElementGuid>8d9b9ded-ba57-4465-a448-0f147db2d5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-link</value>
      <webElementGuid>fe686eba-e892-4545-9cb0-660747def1a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>c54c71be-4111-4f93-8e0c-11b42125b5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formRegister&quot;)/div[@class=&quot;row lang-login-div&quot;]/div[@class=&quot;col-md-12 register-row&quot;]/div[@class=&quot;col-xs-6 have-account-text padding-login-link&quot;]/center[1]/a[@class=&quot;login-link&quot;]</value>
      <webElementGuid>aaa3ba66-4667-4ff9-a089-789b65286735</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick=&quot;redirect_overlay('https://stage.mobipaid.com/login')&quot;])[2]</value>
      <webElementGuid>e77e7415-ed26-47c3-b2ab-eb966acddd76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRegister']/div[9]/div/div[2]/center/a</value>
      <webElementGuid>3745f64a-22eb-4c0b-92fa-41cb5f2cc41d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Login')])[2]</value>
      <webElementGuid>07989a18-afd5-4fde-99cf-15439472edfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='please wait'])[3]/following::a[6]</value>
      <webElementGuid>528a60a2-983b-4152-a5a8-8b4d140be453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Services Agreement'])[2]/preceding::a[1]</value>
      <webElementGuid>7610e8a7-2c1f-420f-a0d1-a68a34c2c27d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='please wait'])[4]/preceding::a[1]</value>
      <webElementGuid>0b9b44d3-5c73-40f6-91eb-e7e5d2d5eb35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/center/a</value>
      <webElementGuid>b0381a9e-ee06-4302-b05f-93dc035c17f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>60e360ec-e95d-4ca5-bec5-3b8cf9a14e2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
